on:
  push:
    tags:
      - "v*-test"

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: install wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      - name: export game
        id: export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./examples/project-godot-4 # build the standard project
          relative_export_path: ./my/build/destination # move export output to this directory relative to git root
          archive_output: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
      - name: create release
        uses: ncipollo/release-action@v1.11.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/* # Added "/*" at the end is glob pattern match for this action
